### ISSUE TITLE
Publish to repo.maven.apache.org

### ISSUE THREAD

**Issue by josephjthomas** [MilkBowl/VaultAPI#133] opened 2021-12-31 00:44 UTC
Do you think you can publish the API to the central maven repository? Jitpack has lots of outages and is by far not as reliable as the the central repository. I encountered several outages over the past months so I couldn't compile my projects.
I hope this is something you would consider.

**Comment by Sleaker** [comment] 2022-01-04 00:15
Duplicate of #90

**Closed by Sleaker** 2022-01-04 00:15 UTC
